### ISSUE TITLE
Request to contribute

### ISSUE THREAD

**Issue by ghost** [krishnagottipalli/cpp_practice#1]
Hey , I would like to contribute to your repository , is there a list of programs that you have to complete (if so can you please share the list ) or is it just general programs

**Comment by 10xsai** [comment]
> Hey , I would like to contribute to your repository , is there a list of programs that you have to complete (if so can you please share the list ) or is it just general programs

hey, @Pandz18 thankyou for the request.
This is what I am thinking to do as of now.
Search Algorithms
Sorting Algorithms
Greedy Algorithms
Divide and Conquer Algorithms
Some common algorithms
Project Euler problems, etc

If you had any other idea please feel free to share.

**Comment by ghost** [comment]
Hey , awesome , I can kinda cover search and sorting 

I was wondering if I could add simple programs too ? Like multiplication , prime , palindrome , series , Arrays , etc ? 
Like from Basics to Advanced kind of thing ?

Cheers

**Comment by 10xsai** [comment]
Hey @Pandz18, that's really great. You are free to contribute anything. But please try to make sure that it passes all the test cases and it's very optimized.

**Comment by ghost** [comment]
Sure ,  I can try my best , if there's something that I can do better please let me know 

When you say test cases , you mean all possible inputs for that program right ?

**Comment by 10xsai** [comment]
Yeah like some edge cases. You don't need to write any test cases. You just check them yourself and make sure that your code is working fine.  If you have any suggestions feel free to share.

**Comment by ghost** [comment]
Awesome , will do 

Thank you
